### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by lresende** [jupyterlab/jupyterlab-toc#118]
As we are approaching the 2.0 JupyterLab release, and we already have a WIP pr for that, I would like to start working on a TOC 1.0.2 release (or should we call it 1.2?) so that we then create a release based on JupyterLab 2.0

**Comment by ian-r-rose** [comment]
Sounds good to me. If we were being completely semver compliant, I thing that the current master targeting JupyterLab 1.0 would be a 2.0 release, and the JupyterLab 2.0 release would get have `@jupyterlab/toc@3.0`.

**Comment by lresende** [comment]
Agreed, I just changed the title of the issue to reflect the direction to a release 2.0.

**Comment by ihightower** [comment]
hi i just upgraded to jupyter lab 2.0. and toc extension couldn't be installed.
i am desperate. how to fix this toc effective now. thank you.

**Comment by lresende** [comment]
You could checkout the pr which brings support for JupyterLab 2.0 and build/install yourself... we plan to release a compatible version soon

**Comment by kgryte** [comment]
@ihightower You can also downgrade back to JLab 1.x and simply migrate once you know that all your favorite extensions have also migrated.

**Comment by lresende** [comment]
Release 2.0 published.
