### ISSUE TITLE
Collapsable Headers?

### ISSUE THREAD

**Issue by infiniteline** [jupyterlab/jupyterlab-toc#12]
Thanks so much for your work on this extension! I've been using Lab more and more and definitely missing TOC2.

Would you consider adding a 'collapse' option for each of the items in the TOC? I imagine it being a small icon to the right of the TOC item that, when selected, hides the cells between that TOC item and the next. This is another JupyterNB extension that is sorely missed. If you need, I can put some nice icons together for you, beta test, and I will look into helping with the code as well.

**Comment by ian-r-rose** [comment]
I think this is a nice idea. Note that the story on the UI for collapsing cells in JupyterLab is still evolving, but I think we could still make something useful as it is.

**Comment by infiniteline** [comment]
Please let me know if I can help. Looks like setting the isHidden property (or use hide() of the CodeEditorWrapper class?) will be all it takes. I'm just not sure how to get the list of nodes for that 'section'. Markdown cells don't automatically become parent to subsequent cells, right? (That would be too convenient!) Alternately, maybe looping through cells from the clicked TOC cell up to the next markdown cell and hide them along the way?

**Comment by kgryte** [comment]
I've submitted a [PR](https://github.com/jupyterlab/jupyterlab-toc/pull/103) which adds uni-directional support for collapsing notebook sections via the ToC. See the following [Binder](https://mybinder.org/v2/gh/kgryte/jupyterlab-toc/collapsible-headers?urlpath=lab%2Ftree%2Fnotebooks%2Fdemo.ipynb) to experiment on a live notebook.
