### ISSUE TITLE
jupyterlab/toc@2.0.0 is not compatible with the current JupyterLab, jupyter version 4.4.0

### ISSUE THREAD

**Issue by GrigoriiTarasov** [jupyterlab/jupyterlab-toc#121]
"@jupyterlab/toc@2.0.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/application
>=0.15.5-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/apputils
>=1.0.10-0 <2.0.0-0     >=3.0.0-0 <4.0.0-0   @jupyterlab/coreutils
>=0.15.5-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/docmanager
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/fileeditor
>=0.15.7-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/notebook
>=0.15.4-0 <0.16.0-0    >=1.0.0-0 <2.0.0-0   @jupyterlab/rendermime

ubuntu 16

**Comment by hannibal1296** [comment]
ubuntu 18 also
