### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by lresende** [jupyterlab/jupyterlab-toc#122]
Now that #116 has been merged with the support for JupyterLab 2.0.0 we need a new release

**Comment by stefansimik** [comment]
Probably not ready yet, just trying and still getting error with command:
`jupyter labextension install @jupyterlab/toc`

Error message:
ValueError: "@jupyterlab/toc@3.0.0" is not a valid npm package

**Comment by stefansimik** [comment]
Problem solved:
I had firewall problem in our company - I found this warning in log:
```
npm WARN registry Using stale data from http://registry.npmjs.org/ because the host is inaccessible -- are you offline?
npm WARN registry Using stale data from http://registry.npmjs.org/ due to a request error during revalidation.
npm notice 
```

After resolving internet connectivity issue, everything works fine.
Thank you for excellent work!

**Comment by lresende** [comment]
This has been released already a few weeks ago.
