### ISSUE TITLE
TOC causes cells in notebook not to render

### ISSUE THREAD

**Issue by billgreenwald** [jupyterlab/jupyterlab-toc#128]
Hi!

I have many notebooks that, without the toc extension installed, render fine w/ about 40 cells, but with toc installed, only render ~10 cells.  The json in the notebook files is not changing, and I have tried installing extensions one at a time and narrowed it down to the toc extension causing the issue.

Jupyter lab 2.1.0 (also happens on 2.0.0)

Let me know what other info you need or i can provide to help troubleshoot.  I love the extension but cannot use it with this bug.

**Comment by chrisking** [comment]
Confirming, with this extension loaded there is no visual indicator from the notebook view that something has changed so if a notebook is accidentally saved with content collapsed, it is not obvious to the viewer and leads to incompleteness in code execution or explanations.

**Comment by athewsey** [comment]
+1 for adding an obvious visible indicator in the notebook when a ToC section is collapsed!

**Comment by billgreenwald** [comment]
I don't think that it was a collapsed cell -- I didn't have to uncollapse anything when i uninstalled the TOC.  And some markdown was missing too. 

Or am I misunderstanding

**Comment by athewsey** [comment]
@billgreenwald As I understand it (per #103), a collapsed ToC section is different from a collapsed cell and uses separate metadata fields in the JSON: So if you uninstalled the ToC extension nothing would handle the metadata and the cells would show. This functionality covers both markdown and code cells...

IMHO, it would be better if there was a visual indication in the notebook itself (not just the twisty in the TOC extension pane) when a section was collapsed. I've struggled myself in the past with not understanding what was going on when a notebook was checked in to source control with a section collapsed!

**Comment by jasongrout** [comment]
I think this is a duplicate of #123. Can we move the conversation there to consolidate the discussion?

This certainly does seem to be a serious issue with this extension, and we welcome help to solve it!

**Comment by billgreenwald** [comment]
Please feel free to close

**Comment by lresende** [comment]
Closing as duplicate of #123 which has been fixed
