### ISSUE TITLE
Merge into Jupyter Lab core?

### ISSUE THREAD

**Issue by rahulpshah** [jupyterlab/jupyterlab-toc#130]
Hi, thanks for the awesome extension. Are there any plans to merge this extension into the core similar to jupyter lab cell tags?

**Comment by lresende** [comment]
There is always this type of chat, but maybe you could influence it more if you could describe what would be the benefits for the end-user if this extension would be moved to JupyterLab.

**Comment by rahulpshah** [comment]
Thanks for the reply. I think the main advantage of having it absorbed into the core is that the end-users don't have to explicitly install this extension on each deployment of JupyterLab. Also, with the extension merged into core we don't have to worry about the compatibility of the extension with the latest version of JupyterLab which has been a common pain point with some other extensions I have been working with. Another advantage of having it merged into core is its increased discoverability for new users who don't know about these extensions backed by Jupyter.

**Comment by jasongrout** [comment]
I think at minimum #123 and #128 should be investigated and solved before considering this for core.

**Comment by lresende** [comment]
@jasongrout #123 has been resolved/merged, if we want to continue with this process, please let me know with the next steps.

**Comment by lresende** [comment]
@rahulpshah some good news. Looks like we have the JLab core contributors in agreement with merging TOC to JLab core and we are going to start the process. Let's continue any additional discussion or technical details on the [JLab team compass](https://github.com/jupyterlab/team-compass/issues/63)
