### ISSUE TITLE
Allow heading numbering to start counting at later Headings and not just Heading 1

### ISSUE THREAD

**Issue by ketozhang** [jupyterlab/jupyterlab-toc#147]
Often times `<h1>` or Markdown `#` is reserved for titles. Titles should not have a heading number however `jupyterlab-toc` provides no option to start counting the heading at later headings like `##`.

## Desired Behavior

```
## Section

<h2>1. Section</h2>
```

## Current Behavior

```
## Section

<h2>0.1 Section</h2>
```

**Comment by chm123** [comment]
Duplicate of #66

**Comment by ketozhang** [comment]
Thanks, closing
