### ISSUE TITLE
An error occurred installing @jupyterlab/toc-extension.

### ISSUE THREAD

**Issue by qizhengyang2017** [jupyterlab/jupyterlab-toc#166]
I used the command line below to install toc-extension. 
```
jupyter labextension install jupyterlab-toc
```

It returned an error:
```
Extension Installation Error
An error occurred installing @jupyterlab/toc-extension.
Error message:
No version of @jupyterlab/toc-extension could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.2.4 <2.3.0          >=3.0.7 <4.0.0 @jupyterlab/application
>=2.2.2 <2.3.0          >=3.0.7 <4.0.0 @jupyterlab/docmanager
>=2.2.2 <2.3.0          >=3.0.7 <4.0.0 
```

```
$jupyter lab --version
2.2.6
```

**Comment by fcollonval** [comment]
Hey @qizhengyang2017 this extension has been merged within JupyterLab starting from v3. Hence the error you're seeing. The good news is that you actually don't need to do anything more than installing JupyterLab 3.

**Comment by DonovanAD** [comment]
Hello, I just installed jupyter lab 3.0.7 and I don't see the TOC anywhere. Here is what I see:

![Screenshot 2021-04-12 at 11 58 40](https://user-images.githubusercontent.com/45604439/114384364-86894c80-9b86-11eb-8947-2cc3a5b0fcf6.png)

Is there something that I can do to fix this?

**Comment by fcollonval** [comment]
@DonovanAD  I transfer your issue as the context is different
