### ISSUE TITLE
'@jupyterlab/toc' is not a valid extension

### ISSUE THREAD

**Issue by jminlee97** [jupyterlab/jupyterlab-toc#175]
Hi, when I try to install this extension, I get the following error message. 

ValueError: "@jupyterlab/toc" is not a valid extension:
No 'jupyterlab' key

Any advice on how to fix this? I wasn't able to find any answers online. My jupyterlab version is 1.2.4 and NodeJS version is 13.14.0.

**Comment by jasongrout** [comment]
As it says in the readme:

> This project is archived. Development is now happening in https://github.com/jupyterlab/jupyterlab.

This extension has been incorporated into JupyterLab itself.
