### ISSUE TITLE
Section headers in non-rendered MD cells always appear as foldable

### ISSUE THREAD

**Issue by OliverEvans96** [jupyterlab/jupyterlab-toc#53]
Hi there,

This extension is looking awesome - thanks for the hard work!

I just wanted to report a very minor bug. It seems that when a markdown cell with a section header is in edit mode (not rendered as markdown), that section has a folding triangle next to it in the left area, even when it doesn't have children to display. Clicking the triangle toggles the icon, but has no other effect.

Demonstrated in Section 2. in the following screenshot.

![2018-09-21-204052_1596x861_scrot](https://user-images.githubusercontent.com/15915043/45911253-cb89df80-bdde-11e8-83d7-dd5a3715043f.png)

When the cell is re-rendered, the triangle disappears, but only after selecting another cell.
Similarly, when the cell is un-rendered, the triangle reappears, but only after selecting another cell.

Again, very minor, but thought it would be good to point out in case it comes up again later.

Thanks!
Oliver

**Comment by ian-r-rose** [comment]
Thanks for the report @OliverEvans96!

**Comment by ian-r-rose** [comment]
Fixed by #70.
