### ISSUE TITLE
Simplify codebase

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab-toc#72]
The new functionality in `@jupyterlab/toc` is awesome, but some if it is kind of hard to maintain and understand. In particular, the notebook generator is over 500 lines long with many branches. We should try to modularize and simplify this.

@markellekelly, do you have any cycles to devote to this, and you able to have a video chat at some point to come up with a strategy?

**Comment by markellekelly** [comment]
Hi @ian-r-rose, I'm definitely available to work on this & would appreciate a video chat to get started!

**Comment by ian-r-rose** [comment]
Great! When works for you?

**Comment by markellekelly** [comment]
I'm free right now! I can also do almost anytime tomorrow.

**Comment by ian-r-rose** [comment]
Cal Poly zoom channel?

**Comment by markellekelly** [comment]
@ian-r-rose I still want to finalize some things next week but here's what i've been working on if you want to take a look/make any suggestions! https://github.com/markellekelly/jupyterlab-toc/tree/simplify

**Comment by ian-r-rose** [comment]
Thanks @markellekelly! Can you open a PR even if it is not done? That will make it easier to see the differences.

**Comment by lresende** [comment]
Is this resolved by #74 and should be closed? Or there are other remaining items to be addressed?

**Comment by kgryte** [comment]
@lresende I think you can go ahead and close this one out.

**Comment by lresende** [comment]
Closed per the discussion above.
