### ISSUE TITLE
Latest Tag (0.6.0)  not compatible with Jupyter1.0

### ISSUE THREAD

**Issue by alexiswl** [jupyterlab/jupyterlab-toc#81]
Hi there when installing this extension I get the following error:

Conflicting Dependencies:
JupyterLab              Extension              Package
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/application
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/apputils
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/docmanager
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/fileeditor
>=1.0.0-alpha.4 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/notebook
>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/rendermime

Steps to reproduce
$ jupyter-lab --version
1.0.0a1

$jupyter labextension install @jupyterlab/toc

Would you mind creating a new tag that's compatible with Jupyter1.0

I was able to download and install the dev version in the interim

Kind Regards,
Alexis.

**Comment by ian-r-rose** [comment]
Hi @alexiswl, I just published a prerelease under the `@next` tag. Closing as fixed, but let me know if this doesn't work for you.
