### ISSUE TITLE
Cannot install v0.3.1

### ISSUE THREAD

**Issue by ksil91** [jupyterlab/jupyterlab-toc#86]
Version 0.2.0 no longer worked with my version of jupyterlab (0.33.12, python 2.7 ), it would just show all headings as the same size and unnested. I tried to update it with:

`sudo jupyter labextension install @jupyterlab/toc'
and
` sudo jupyter labextension install @jupyterlab/toc@0.3.1'

Both times it would download v0.3.1 but then seem to install v0.2.0. I tried installing v0.1.0 and that  did install correctly but was also not compatible.

`
jupyterlab-toc-0.6.0.tgz
Incompatible extension:

"@jupyterlab/toc@0.6.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.3 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/rendermime
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/docmanager
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/fileeditor
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/apputils
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/notebook

Found compatible version: 0.3.1
> /usr/bin/npm pack @jupyterlab/toc@0.3.1
npm notice 
npm notice 📦  @jupyterlab/toc@0.3.1
npm notice === Tarball Contents === 
npm notice 2.1kB  package.json       
npm notice 1.5kB  LICENSE            
npm notice 1.2kB  README.md          
npm notice 304B   lib/extension.d.ts 
npm notice 3.2kB  lib/extension.js   
npm notice 1.6kB  lib/generators.d.ts
npm notice 12.4kB lib/generators.js  
npm notice 81B    lib/index.d.ts     
npm notice 373B   lib/index.js       
npm notice 2.1kB  lib/registry.d.ts  
npm notice 1.3kB  lib/registry.js    
npm notice 3.2kB  lib/toc.d.ts       
npm notice 4.9kB  lib/toc.js         
npm notice 1.4kB  style/index.css    
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/toc                         
npm notice version:       0.3.1                                   
npm notice filename:      jupyterlab-toc-0.3.1.tgz                
npm notice package size:  9.5 kB                                  
npm notice unpacked size: 35.5 kB                                 
npm notice shasum:        0e46f30a3f99174b3e460448968ecc2bc6501496
npm notice integrity:     sha512-nWhBFajzgK5UM[...]EXQK0f7bwxxng==
npm notice total files:   14                                      
npm notice 
jupyterlab-toc-0.3.1.tgz

"jupyterlab-toc@0.2.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.3 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/rendermime
>=2.0.3 <3.0.0          >=1.0.0 <2.0.0   @jupyterlab/coreutils
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/docmanager
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/fileeditor
>=0.17.2 <0.18.0        >=0.16.2 <0.17.0 @jupyterlab/apputils
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/notebook
`

**Comment by lresende** [comment]
It has been a while and JupyterLab is now in version 1.2.6 which works fine with toc v1.0.1
