### ISSUE TITLE
Python file support

### ISSUE THREAD

**Issue by sballin** [jupyterlab/jupyterlab-toc#9]
This extension is great! Just wanted to suggest a feature: instead of going blank when editing a Python file, it could show a skeleton of the code with the class/method lines.

**Comment by ian-r-rose** [comment]
I think that's a nice idea. It could even be a good test of the [API](https://github.com/ian-r-rose/jupyterlab-toc/blob/master/src/generators.ts#L57) that I've been trying to design for different types of files, in case somebody wanted to try... :wink:

**Comment by mocquin** [comment]
I second that ! It's the only file type missing in a standard python workflow (having nb and md).

**Comment by stefansimik** [comment]
Adding TOC for basic structure of *.py files would bring new level of comfort in orientation.
It is really **very missing** feature.

(Classes and methods would be really enough for high practical usability)

**Comment by marthacryan** [comment]
I'm going to start working on this issue.
