### ISSUE TITLE
Toc does not appear in the sidebar with Jupyterlab 1.0.0 

### ISSUE THREAD

**Issue by marcevrard** [jupyterlab/jupyterlab-toc#91]
Since I've updated from Jupyterlab 1.0.0-rc0 to Jupyterlab 1.0.0, the Toc tab's disappeared from the sidebar. 
Versions :
```
@jupyter-widgets/jupyterlab-manager v1.0.0  enabled  OK
@jupyterlab/toc v1.0.0-rc.0  enabled  OK
Python 3.7.3
MacOS 10.14.5.
```
The version of the TOC extension is indeed 1.0.0-rc.0, thus I may just need to wait for the next release, though no compatibility issues were reported.

**Comment by marcevrard** [comment]
Seems like other extensions are not showing up as well, maybe a problem in Jupyterlab?

**Comment by marcevrard** [comment]
A clean install has fixed the problem for TOC, though the problem seems to persist for `@jupyterlab/celltags v0.1.5`.

**Comment by ian-r-rose** [comment]
Thanks for updating with a solution @marcevrard!

**Comment by marcevrard** [comment]
My pleasure, thank you for your great work @ian-r-rose!

**Comment by jtackm** [comment]
My sidebar is also not showing on the following setup
```
JupyterLab v1.0.5
Known labextensions:
   app dir: /mnt/mnemo3/janko/anaconda3/share/jupyter/lab
        @jupyterlab/toc v1.0.1  enabled  OK
---
jupyter                            1.0.0
```
I tried reinstalling both jupyter and jupyterlab (pip), as well as reinstalling the toc extension and removing former workspaces, but unfortunately to no effect. Any suggestions?

**Comment by jtackm** [comment]
Sorry for the spam, I didn't see that the side menu button had appeared after the re-install. Everything works fine now, thanks for the awesome extension!
