### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-toc#92]
Is there a plan to update this to 1.0.0? I see have a 1.0.0-rc release but not a final release.

https://www.npmjs.com/package/@jupyterlab/toc/v/1.0.0-rc.0

**Comment by ian-r-rose** [comment]
Sorry, I was travelling and got a bit behind. I've published a 1.0.0! Closing as fixed, but let me know if you have any troubles.
