### ISSUE TITLE
sidebar became wierd after installation 

### ISSUE THREAD

**Issue by chwang1991** [jupyterlab/jupyterlab-toc#98]
Hi, 

![Snipaste_2019-09-04_18-59-52](https://user-images.githubusercontent.com/39996696/64249494-590a0500-cf46-11e9-848f-f4b8dadfc203.png)

is there anyone encounter the same problem as the above figure shows?

**Comment by Albocoder** [comment]
Same for me. I solved this way:
```
jupyter labextension uninstall @jupyterlab/toc
jupyter lab clean
jupyter lab build
```

If problem persists:
`pip install jupyterlab --upgrade`

**Comment by ian-r-rose** [comment]
There were some issues with the release of JupyterLab 1.1 that caused some problems like this, though they have since been fixed in a patch release. Can you try upgrading JupyterLab and reinstalling the extension?

**Comment by codydunne** [comment]
@ian-r-rose when I had the same issue your suggestion worked. I upgraded to jupyter lab 1.1.2.

```
pip install jupyterlab --upgrade
jupyter labextension install @jupyterlab/toc
```

**Comment by chwang1991** [comment]
> There were some issues with the release of JupyterLab 1.1 that caused some problems like this, though they have since been fixed in a patch release. Can you try upgrading JupyterLab and reinstalling the extension?

yes it works, thank you so much!
